import type { Achievement } from '../types';

export const mockAchievements: Achievement[] = [
  {
    id: 'ach-1',
    student: { id: 'stu-1', nickname: '小明', avatarEmoji: '🧑', gradeId: 6, classCode: '3班' },
    course: { title: '行李箱整理', taskGroupId: 'tidy' },
    title: '帮妈妈整理了春游行李箱！',
    description: '用卷叠法把全家的衣服都整理好了，箱子空间多了好多，妈妈夸我整理得比她还好！',
    images: ['🧳'],
    evalAttitude: 5, evalSkill: 5, evalResult: 5,
    likesCount: 18,
    createdAt: '2026-03-20',
    isLikedByMe: false,
  },
  {
    id: 'ach-2',
    student: { id: 'stu-2', nickname: '小雨', avatarEmoji: '👧', gradeId: 6, classCode: '1班' },
    course: { title: '水仙花雕刻及养护', taskGroupId: 'farm' },
    title: '我的水仙花开啦🌸',
    description: '雕刻完养了两周，今天终于开花了！白色花瓣配着黄色花心，香香的，摆在书桌上超好看！',
    images: ['🌸'],
    evalAttitude: 5, evalSkill: 5, evalResult: 5,
    likesCount: 34,
    createdAt: '2026-03-18',
    isLikedByMe: true,
  },
  {
    id: 'ach-3',
    student: { id: 'stu-3', nickname: '小强', avatarEmoji: '👦', gradeId: 6, classCode: '2班' },
    course: { title: '中国结的编织', taskGroupId: 'craft' },
    title: '编了一个红色平结手链',
    description: '第一次编中国结，刚开始总是绕错方向，后来慢慢摸清规律了，最后编出来送给了奶奶，她说很好看！',
    images: [],
    evalAttitude: 4, evalSkill: 4, evalResult: 4,
    likesCount: 22,
    createdAt: '2026-03-15',
    isLikedByMe: false,
  },
  {
    id: 'ach-4',
    student: { id: 'stu-4', nickname: '小美', avatarEmoji: '👱‍♀️', gradeId: 6, classCode: '4班' },
    course: { title: '布艺小包的设计与制作', taskGroupId: 'craft' },
    title: '做了一个粉色零钱包💜',
    description: '自己设计了一个圆形零钱包，用了粉色棉布，还绣了一个小星星，安上拉链后装硬币超方便！',
    images: ['👜'],
    evalAttitude: 5, evalSkill: 5, evalResult: 5,
    likesCount: 41,
    createdAt: '2026-03-12',
    isLikedByMe: false,
  },
  {
    id: 'ach-5',
    student: { id: 'stu-5', nickname: '小杰', avatarEmoji: '🧒', gradeId: 6, classCode: '5班' },
    course: { title: '面包的烘焙', taskGroupId: 'cook' },
    title: '烤出来的面包超香！',
    description: '揉面揉了好久，手臂都有点酸了，但是烤出来的面包金黄金黄的，咬一口特别松软，全家都说好吃！',
    images: ['🍞'],
    evalAttitude: 5, evalSkill: 5, evalResult: 5,
    likesCount: 47,
    createdAt: '2026-03-10',
    isLikedByMe: true,
  },
  {
    id: 'ach-6',
    student: { id: 'stu-6', nickname: '小琳', avatarEmoji: '👩', gradeId: 6, classCode: '3班' },
    course: { title: '金属丝花瓶架的设计与制作', taskGroupId: 'industry' },
    title: '给小玻璃瓶做了一个支架',
    description: '用铝丝弯出了一个三脚架，把家里的小玻璃瓶放进去，再插上一支干花，摆在窗台上很有设计感！',
    images: [],
    evalAttitude: 4, evalSkill: 4, evalResult: 4,
    likesCount: 15,
    createdAt: '2026-03-08',
    isLikedByMe: false,
  },
  {
    id: 'ach-7',
    student: { id: 'stu-7', nickname: '小浩', avatarEmoji: '🧑', gradeId: 6, classCode: '2班' },
    course: { title: '布艺挂件的设计与制作', taskGroupId: 'craft' },
    title: '做了一只棉花糖小兔子🐰',
    description: '设计了一个兔子造型挂件，耳朵用了粉色布，眼睛用黑色扣子，填了很多棉花，软软的！',
    images: ['🎀'],
    evalAttitude: 5, evalSkill: 5, evalResult: 5,
    likesCount: 29,
    createdAt: '2026-03-05',
    isLikedByMe: false,
  },
  {
    id: 'ach-8',
    student: { id: 'stu-8', nickname: '小涵', avatarEmoji: '👧', gradeId: 6, classCode: '1班' },
    course: { title: '电烤箱的使用与维护', taskGroupId: 'appliance' },
    title: '学会了烤箱的正确用法',
    description: '认真学习了烤箱各部件，还把烤盘和烤网清洗得干干净净，老师说我操作规范，很安全！',
    images: [],
    evalAttitude: 4, evalSkill: 4, evalResult: 4,
    likesCount: 11,
    createdAt: '2026-03-01',
    isLikedByMe: false,
  },
];